app/modales/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'modales_blueprint',
    __name__,
    url_prefix='/modales',
    template_folder='templates',
    static_folder='static'
)

app/modales/routes.py
from app.modales import blueprint
from flask import render_template, request, jsonify, redirect
from flask_login import login_required
from bcrypt import checkpw
from app import db, login_manager
from app.db_models.models import *
from sqlalchemy import and_


@blueprint.route('/<template>')
@login_required
def route_template(template):
    return render_template(template + '.html')

###### agregar modales



@blueprint.route('/agregar_categoria', methods=['GET', 'POST'])
@login_required
def agregar_categoria():
    if request.form:
        data = request.form
        categoria = Categorias(nombre=data["nombre"], tipo=data["tipo"]) 
        db.session.add(categoria)
        db.session.commit()   
        return redirect("/administracion/otros")     



@blueprint.route('/agregar_centro', methods=['GET', 'POST'])
@login_required
def agregar_centro():
    if request.form:
        data = request.form
        centro = CentrosNegocio(nombre=data["nombre"], numero=data["numero"],  tipo=data["tipo"],  direccion=data["direccion"],  
        empresa_id=data["empresa"],  arrendadora=data["arrendadora"],  comentario=data["comentario"], efectivo_1=data["efectivo_1"], efectivo_2=data["efectivo_2"]  ) 
        db.session.add(centro) 
        db.session.commit()   
        return redirect("/administracion/centros_negocios")

@blueprint.route('/get_data_editar_centro/<cid>', methods=['GET', 'POST'])
@login_required
def get_data_editar_centro(cid):
  centro = CentrosNegocio.query.get(cid)
  return jsonify(id=centro.id, numero=centro.numero, nombre=centro.nombre, tipo=centro.tipo, direccion= centro.direccion,  empresa_id=centro.empresa_id, arrendadora= centro.arrendadora, comentario=centro.comentario, efectivo_1=centro.efectivo_1, efectivo_2=centro.efectivo_2) 


@blueprint.route('/editar_centro', methods=['GET', 'POST'])
@login_required
def editar_centro():
    if request.form:
        data = request.form
        print(data)
        centro = CentrosNegocio.query.get(data["id"])

        centro.nombre=data["nombre"]
        centro.numero=data["numero"]
        centro.tipo=data["tipo"]
        centro.direccion=data["direccion"]
        centro.empresa_id=data["empresa"]  
        centro.arrendadora=data["arrendadora"]
        centro.comentario=data["comentario"]
        centro.efectivo_1=data["efectivo_1"]
        centro.efectivo_2=data["efectivo_2"]
        db.session.add(centro) 
        db.session.commit()   
        return redirect("/administracion/centros_negocios")  





@blueprint.route('/agregar_concepto', methods=['GET', 'POST'])
@login_required
def agregar_concepto():
    if request.form:
        data = request.form
        if (data["categoria"]):
                categoria=data["categoria"]
        if (data["categoria2"]):
                categoria=data["categoria2"]
        concepto = Conceptos(nombre=data["nombre"], categoria_id=categoria) 
        db.session.add(concepto)
        db.session.commit()   
        return redirect("/administracion/otros")      


@blueprint.route('/agregar_empresa', methods=['GET', 'POST'])
@login_required
def agregar_empresa():
    if request.form:
        data = request.form
        empresa = Empresas(nombre=data["nombre"]) 
        db.session.add(empresa)
        db.session.commit()   
        return redirect("/administracion/otros")
    

        
#agregar_forma pago
@blueprint.route('/agregar_forma_pago', methods=['GET', 'POST'])
@login_required
def agregar_forma_pago():
        if request.form:
                data = request.form
                forma_pago= FormasPago(nombre=data["nombre"])
                db.session.add(forma_pago)
                db.session.commit()   
                return redirect("/administracion/otros")   
    

@blueprint.route('/agregar_tipo_ingreso', methods=['GET', 'POST'])
@login_required
def agregar_tipo_ingreso():
    if request.form:
        data = request.form
        tipo_ingreso = Tipo_Ingreso(tipo = data["tipo"]) 
        db.session.add(tipo_ingreso)
        db.session.commit()   
        return redirect("/administracion/otros")     
    
    
    

app/modales/templates/modal_agregar_categoria.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_agregar_categoria" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <form class="form-horizontal form-label-left" id="user_inputs" method="POST"
        action="{{ url_for('modales_blueprint.agregar_categoria') }}">
        <div class="modal-header">
          <h3 class="modal-title" id="largeModalLabel"> Agregar Cuenta de Mayor</h3>
        </div>
        <div class="modal-body">
          <div class="row" style="margin-bottom:20px !important">
            <div class="col-sm-6">
              <label for="nombre"> Cuenta de Mayor </label>
              <input type='text' class="form-control" name="nombre" autocomplete="off" />
            </div>
            <div class="col-sm-6">
                <label for="tipo"> Egreso o Ingreso </label>
              <select class="selectpicker"  data-live-search="true" name="tipo" title="Selecciona.." data-width="100%">
                <option value="egreso"> Egreso</option>
                <option value="ingreso"> Ingreso</option>                
              </select>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Agregar</button>
          <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
            <i class="material-icons">close</i>
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

app/modales/templates/modal_agregar_categoria_beneficiario.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_agregar_categoria_beneficiario" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form class="form-horizontal form-label-left" method="POST" action="{{ url_for('administracion_blueprint.agregar_categoria_beneficiario',  beneficiario_id=beneficiario.id) }}">
                <div class="modal-header">
                    <h3 class="modal-title" id="largeModalLabel"> Asignar Cuenta de Mayor</h3>
                </div>
                <div class="modal-body">
                    <div class="row" style="margin-bottom:20px !important">
                        <div class="col-sm-12">
                            <label for="nombre"> Cuenta de Mayor </label>
                            <select class="selectpicker" multiple data-live-search="true" name="categoria" title="Seleccione una Cuenta de Mayor..."
                            data-width="100%">

                            {% for categoria in categorias %}
                            <option value="{{categoria.id}}"> {{ categoria.nombre }} </option>
                            {% endfor %}
                        </select>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Agregar</button>
                    <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                        <i class="material-icons">close</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

app/modales/templates/modal_agregar_centro.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_agregar_centro" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <form class="form-horizontal form-label-left" id="user_inputs" method="POST" action="{{ url_for('modales_blueprint.agregar_centro') }}">
                    <div class="modal-header">
                        <h3 class="modal-title" id="largeModalLabel"> Agregar Centro de Negocios</h3>
                    </div>
                    <div class="modal-body">
                        <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12 col-md-6">
                                <label for="nombre"> Centro de Negocios </label>
                                <input type='text' class="form-control" name="nombre" data-validation="required" autocomplete="false" />
                            </div>
                            <div class="col-sm-12 col-md-6">
                                    <label for="beneficiario"> Empresa </label><br>
                                    <select class="selectpicker" id="empresa" name="empresa" data-validation="required"
                                        data-live-search="true" title="Seleccione una Empresa..."
                                        data-width="100%">
                                        {% for empresa in empresas %}
                                        <option value="{{empresa.id}}"> {{ empresa.nombre }} </option>
                                        {% endfor %}
                                    </select>
                                
                            </div>
                        </div>

                        <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12 col-md-6">
                                    <label for="numero"> Numero del Centro de Negocios </label>
                                    <input type='text' class="form-control" name="numero" autocomplete="false" />
                               
                            </div>
                            <div class="col-sm-12 col-md-6">
                                    <label for="beneficiario"> Tipo </label><br>
                                    <select class="selectpicker" id="tipo" name="tipo" data-validation="required"
                                      data-live-search="true" title="Seleccione un Tipo de Negocios..."
                                      data-width="100%">
                                      <option value="Tienda fisica">Tienda fisica</option>
                                      <option value="E-commerce">E-commerce</option>
                                      <option value="Mayorista">Mayorista</option>
                                      <option value="Compras">Compras</option>
                                      <option value="Administración">Administración</option>
                                      <option value="Socios">Socios</option>
                                      <option value="Operaciones">Operaciones</option>
                                    </select>
                              
                            </div>
                        </div>

                        <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12 col-md-6">
                                    <label for="direccion"> Dirección </label>
                                    <input type='text' class="form-control" name="direccion" autocomplete="false" />
                            </div>
                            <div class="col-sm-12 col-md-6">
                                    <label for="arrendadora"> Arrendadora </label>
                                    <input type='text' class="form-control" name="arrendadora" autocomplete="false" />
                            </div>
                        </div>

                        <div class="row" style="margin-bottom:20px !important">
                                <div class="col-sm-12">
                                    <label for="comentario"> Comentario </label>
                                    <textarea name="comentario" id="comentario" style="width:100%"></textarea>
                                 </div>
                        </div>

                        <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12 col-md-6">
                                <label for="efectivo_1"> Efectivo 1 </label><br>
                                <select class="selectpicker" id="efectivo_1_editar" name="efectivo_1" data-validation="required"
                                data-live-search="true" title="Seleccione una cuenta de banco"
                                data-width="100%">
                                {% for cuenta in cuentas %}
                                <option value="{{cuenta.id}}"> {{ cuenta.nombre }} </option>
                                {% endfor %}
                                </select>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                    <label for="efectivo_2"> Efectivo 2 </label><br>
                                    <select class="selectpicker" id="efectivo_2_editar" name="efectivo_2" data-validation="required"
                                    data-live-search="true" title="Seleccione una cuenta de banco"
                                    data-width="100%">
                                    {% for cuenta in cuentas %}
                                <option value="{{cuenta.id}}"> {{ cuenta.nombre }} </option>
                                {% endfor %}
                                </select>
                            </div>
                        </div>

                    </div>
        
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Agregar</button>
                        <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                            <i class="material-icons">close</i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

app/modales/templates/modal_agregar_contacto_cliente.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_agregar_contacto_cliente" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form class="form-horizontal form-label-left" method="POST" action="{{ url_for('administracion_blueprint.agregar_contacto_cliente', cliente_id=cliente.id) }}">
  
                <div class="modal-header">
                    <h3 class="modal-title" id="largeModalLabel"> Agregar Contacto</h3>
                </div>
                <div class="modal-body">
                    <table id="table" style="table-layout: fixed;" class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Correo</th>
                                <th>Teléfono</th>
                                <th>Extensión</th>
                                <th>Puesto</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <input type="text" name="nombre_contacto" style="width:100%">
                                </td>
                                <td>
                                    <input type="email" name="correo_contacto" style="width:100%">
                                </td>
                                <td>
                                    <input type="tel" name="telefono_contacto" style="width:100%">
                                </td>
                                <td>
                                    <input type="number" name="extension_contacto" style="width:100%">
                                </td>
                                <td>
                                    <input class="form-control" type="text" name="puesto_contacto">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
  
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Agregar Contacto</button>
                    <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                        <i class="material-icons">close</i>
                    </button>
                </div>
            </form>
  
        </div>
    </div>
  </div>
  

app/modales/templates/modal_agregar_cuenta.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_agregar_cuenta" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <form class="form-horizontal form-label-left" id="user_inputs" method="POST" action="{{ url_for('conciliacion_blueprint.agregar_cuenta') }}">
                    <div class="modal-header">
                        <h3 class="modal-title" id="largeModalLabel"> Agregar Cuenta</h3>
                    </div>
                    <div class="modal-body">
                    <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12 col-md-6">
                                <label for="nombre"> Nombre </label>
                                <input type='text' class="form-control" name="nombre" data-validation="required" autocomplete="false"/>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <label for="beneficiario"> Empresa </label><br>
                                <select class="selectpicker" id="empresa" name="empresa" data-validation="required"
                                    data-live-search="true" title="Seleccione una Empresa..."
                                    data-width="100%">
                                    {% for empresa in empresas %}
                                    <option value="{{empresa.id}}"> {{ empresa.nombre }} </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12 col-md-6">
                                <label for="banco"> Banco </label>
                                <input type='text' class="form-control" name="banco" autocomplete="false"/>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <label for="numero"> Numero</label>
                                <input type='number' class="form-control" name="numero" autocomplete="false"/>
                            </div>
                        </div>
                    
                        <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12 col-md-6">
                                <label for="saldo">Saldo Inicial</label>
                                <input type='text' data-validation="number" data-validation-allowing="float" class="form-control" name="saldo" />
                            </div>
                        </div>

                        <div class="row" style="margin-bottom:20px !important">
                                <div class="col-sm-12">
                                    <label for="arrendadora"> Comentario </label>
                                    <textarea name="comentario" id="comentario" style="width:100%"></textarea>
                                 </div>
                        </div>

                    </div>
        
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Agregar Cuenta</button>
                        <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                            <i class="material-icons">close</i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

app/modales/templates/modal_agregar_detalle_ingresos.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_agregar_detalle_ingresos" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form class="form-horizontal form-label-left" method="POST" action="{{ url_for('ingresos_blueprint.agregar_detalle', ingreso_id=ingreso.id) }}">
                <div class="modal-header">
                    <h3 class="modal-title" id="largeModalLabel"> Agregar detalle a la cuenta por pagar</h3>
                </div>
                <div class="modal-body">
                <div class="row" style="margin-bottom:20px !important">
                        <div class="col-sm-12 col-md-6">
                                <label for="beneficiario"> Centro de negocios </label><br>
                                <select class="selectpicker"  data-live-search="true" 
                                name="centro_negocios" title="Seleccione un Centro de Negocios..." data-width="100%">
                                {% for centro in centros_negocio %}
                                <option value="{{centro.id}}"> {{ centro.nombre }} </option>
                                {% endfor %}
                              </select>
                        </div>
                        <div class="col-sm-12 col-md-6">
                                <label for="proveedor"> Cliente </label><br>
                                <select class="selectpicker"  data-live-search="true" 
                                name="cliente" title="Seleccione un Cliente..."
                                 data-width="100%">
                                 {% for cliente in clientes %}
                                 <option value="{{cliente.id}}"> {{cliente.nombre }} </option>
                                 {% endfor %}
                               </select>
                            
                        </div>
                    </div>
                    <div class="row" style="margin-bottom:20px !important">
                        <div class="col-sm-12 col-md-6">
                            <label for="categoria"> Categoría </label>
                            <select class="selectpicker" data-live-search="true" 
                              name="categoria" title="Seleccione una Categoria..."
                              data-width="100%">
                              {% for categoria in categorias %}
                              <option value="{{categoria.id}}"> {{ categoria.nombre }} </option>
                              {% endfor %}
                            </select>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <label for="concepto"> Concepto</label>
                            <select class="selectpicker"  
                            data-live-search="true" name="concepto" title="Seleccione un Concepto..." data-width="100%">
                            {% for concepto in conceptos %}
                            <option value="{{concepto.id}}"> {{ concepto.nombre }} </option>
                            {% endfor %}
                          </select>
                        </div>
                    </div>
                
                    <div class="row" style="margin-bottom:20px !important">
                        <div class="col-sm-12 col-md-6">
                            <label for="monto">Monto</label>
                            <input type='number' class="form-control" name="monto" />
                        </div>
                        <div class="col-sm-12 col-md-6">
                                <label for="numero_control"># de control</label>
                                <input type='text' class="form-control" name="numero_control" />
                            </div>
                    </div>

                    <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12">
                                <label for="arrendadora"> Comentario </label>
                                <textarea name="comentario" id="comentario" style="width:100%"></textarea>
                             </div>
                    </div>

                </div>
    
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Agregar Detalle</button>
                    <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                        <i class="material-icons">close</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

app/modales/templates/modal_agregar_empresa.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_agregar_empresa" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <form class="form-horizontal form-label-left" id="user_inputs" method="POST" action="{{ url_for('modales_blueprint.agregar_empresa') }}">
                    <div class="modal-header">
                        <h3 class="modal-title" id="largeModalLabel"> Agregar Empresa</h3>
                    </div>
                    <div class="modal-body">
                        <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12">
                                <label for="nombre"> Empresa </label>
                                <input type='text' class="form-control" name="nombre" data-validation="required" />
                            </div>
                        </div>
                    </div>
        
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Agregar</button>
                        <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                            <i class="material-icons">close</i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

app/modales/templates/modal_agregar_forma_pago.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_agregar_forma_pago" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <form class="form-horizontal form-label-left" id="user_inputs" method="POST" action="{{ url_for('modales_blueprint.agregar_forma_pago') }}">
                    <div class="modal-header">
                        <h3 class="modal-title" id="largeModalLabel"> Agregar Forma de Pago</h3>
                    </div>
                    <div class="modal-body">
                        <div class="row" style="margin-bottom:20px !important">
                            <div class="col-sm-12">
                                <label for="nombre"> Forma de pago </label>
                                <input type='text' class="form-control" name="nombre" />
                            </div>
                        </div>
                    </div>
        
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Agregar</button>
                        <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                            <i class="material-icons">close</i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

app/modales/templates/modal_editar_cliente.html
<!-- Modal pagos -->
<div class="modal fade" id="modal_editar_cliente" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form class="form-horizontal form-label-left" method="POST" action="{{ url_for('administracion_blueprint.editar_cliente') }}">
  
                <div class="modal-header">
                    <h3 class="modal-title" id="largeModalLabel"> Editar Cliente</h3>
                </div>
                <div class="modal-body">
                  <div class="cliente-here"></div>
                </div>
  
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Editar Cliente</button>
                    <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                        <i class="material-icons">close</i>
                    </button>
                </div>
            </form>
  
        </div>
    </div>
  </div>
  <script src="{{ url_for('static', filename='vendors/jquery/dist/jquery.min.js') }}"></script>
  
  <script>

  </script>

app/modales/templates/modal_editar_multiple.html
<div class="modal fade" id="modal_editar_multiple" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="largeModalLabel">Editar</h4>
        </div>
        <form class="form-horizontal form-label-left" method="POST" action="{{ url_for('administracion_blueprint.editar_multiple') }}">

                <div class="modal-body">
                        <div class="editar-multiple-here"></div>
                </div>
    
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Editar</button>
                    <button type="button" class="btn btn-link btn-circle waves-effect btn-close" data-dismiss="modal">
                        <i class="material-icons">close</i>
                    </button>
                </div>
            </form>
     

        </div>
    </div>
</div>